const urls = {
  api: "/api",
  user: "/user",
  users: "/users",
  roles: "/roles",
  customers: "/customers",
  customer: "/customer",
  permissions: "/permissions",
  create: "/create",
  role: "/role",
  edit: "/edit",
  login: "/login",
  categories: "categories",
  ads: "/ads/",
  checkToken: "/checkUser",
  host: "http://65.21.180.103",
  postPermission: "/api/role/create",
  toggleBlock: "/toggleBlock",
  delete: "/delete",
  cities: "/cities",
  block: "/block",
  unblock: "/unblock",
  block_reasons: "/block-reasons",
};
export default urls;
